name: Remove PR docker image

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_call:
    inputs:
      tag:
        required: false
        type: string 

jobs:
  remove_image:
    name: Remove image
    runs-on: ubuntu-latest

    steps:
      - name: Find package id and delete
        run: |
          tag=${{ inputs.tag }}
          if [ -z "${tag}" ]; then
            tag=pr-${{ github.event.number }}
          fi

          echo Retriving image with tag ${tag}

          package_id=$(curl -L -s \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/users/sabowski/packages/container/ecobee-exporter/versions \
            | jq -r --arg tag "$tag" '.[] | select(.metadata.container.tags | index($tag)) | .id')
          
          echo package id is ${package_id:-not found}

          echo Deleting image

          curl -L -X DELETE -s -w "%{http_code}" \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/users/sabowski/packages/container/ecobee-exporter/versions/${package_id}
